version: '3'
services:
  influxdb:
    image: "influxdb"
    ports:
      - 8086:8086
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      #   - 'influxdb:/var/lib/influxdb'
      - ./config/:/etc/influxdb
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password


  chronograf:
    image: chronograf:latest
    volumes:
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
